name: lem
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - genomepy
  - cooltools
  - hoomd
  - gsd
  - plotnine
  - pysam
  - rowan
  - cupy
  - fresnel
  - prompt_toolkit
  - ipython
  - ipykernel
