name: lem
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - httpx<=0.28.1
  - cooltools
  - hoomd
  - gsd
  - plotnine
  - pysam
  - rowan
  - cupy
  - fresnel
  - prompt_toolkit
  - ipython
  - ipykernel
  - py2bit
  - crossmap
